/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/peONeJMjTlP
 */
import Link from "next/link"
import { Button } from "@/components/ui/button-secondary"
import { Button as Button1 } from "@/components/ui/button-main"

import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card-secondary"
import { Input } from "@/components/ui/input-secondary"
export default function Events() {
  return (           <section
    style={{
      color: "#1b2945",
     padding : "2rem",
    }}
     className="py-8">
      <div className="container mx-auto">
        <h2 className="text-2xl font-bold text-gray-800"> HALLS</h2>
        <div className="mt-4 flex space-x-2">
          <Select>
            <SelectTrigger id="weekdays">
              <SelectValue placeholder="Weekdays" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="monday">Monday</SelectItem>
              <SelectItem value="tuesday">Tuesday</SelectItem>
              <SelectItem value="wednesday">Wednesday</SelectItem>
              <SelectItem value="thursday">Thursday</SelectItem>
              <SelectItem value="friday">Friday</SelectItem>
              <SelectItem value="saturday">Saturday</SelectItem>
              <SelectItem value="sunday">Sunday</SelectItem>
            </SelectContent>
          </Select>
          <Select>
            <SelectTrigger id="event-type">
              <SelectValue placeholder="Event Type" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="conference">Conference</SelectItem>
              <SelectItem value="seminar">Seminar</SelectItem>
              <SelectItem value="workshop">Workshop</SelectItem>
            </SelectContent>
          </Select>
          <Select>
            <SelectTrigger id="category">
              <SelectValue placeholder="Category" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="technology">Technology</SelectItem>
              <SelectItem value="business">Business</SelectItem>
              <SelectItem value="education">Education</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="mt-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <Card className="w-full">
            <CardHeader>
              <CardTitle>Consists of 200 chairs and a display screen.</CardTitle>
              <CardDescription>We’ll get you directly seated and inside for you to enjoy the show.</CardDescription>
            </CardHeader>
            <CardContent>
              <img
                alt="Event Image"
                className="h-[200px] w-full object-cover"
                height="200"
                src="/hall1.jpg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300" />
            </CardContent>
            <CardFooter className="flex justify-between">
              <span>More Info</span>
              <a href="/events/book">
            <Button
              className="mt-6 bg-yellow-400 text-gray-900 hover:bg-yellow-500"
              variant="default">
              book hall
            </Button>
            </a>              </CardFooter>
          </Card>
          <Card className="w-full">
            <CardHeader>
              <CardTitle>Consists of 20 chairs and a display screen</CardTitle>
              <CardDescription>We’ll get you directly seated and inside for you to enjoy the show.</CardDescription>
            </CardHeader>
            <CardContent>
              <img
                alt="Event Image"
                className="h-[200px] w-full object-cover"
                height="200"
                src="/hall3.jpg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300" />
            </CardContent>
            <CardFooter className="flex justify-between">
              <span>More Info</span>
              <a href="/events/book">
                <Button
                  className="mt-6 bg-yellow-400 text-gray-900 hover:bg-yellow-500"
                  variant="default">
              book hall
                </Button>
              </a>              </CardFooter>
          </Card>
          <Card className="w-full">
            <CardHeader>
              <CardTitle>Consists of 40 chairs and a display screen.</CardTitle>
              <CardDescription>We’ll get you directly seated and inside for you to enjoy the show.</CardDescription>
            </CardHeader>
            <CardContent>
              <img
                alt="Event Image"
                className="h-[200px] w-full object-cover"
                height="200"
                src="/hall2.jpg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300" />
            </CardContent>
            <CardFooter className="flex justify-between">
              <span>More Info</span>
              <a href="/events/book">
            <Button
              className="mt-6 bg-yellow-400 text-gray-900 hover:bg-yellow-500"
              variant="default">
              book hall
            </Button>
            </a>              </CardFooter>
          </Card>


        </div>
      </div>
    </section>

  );
}

