/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/peONeJMjTlP
 */
import Link from "next/link"
import { Button } from "@/components/ui/button-secondary"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card-secondary"
import { Input } from "@/components/ui/input-secondary"

export function events() {
  return (
    (<div className="flex flex-col">
      <nav className="bg-white px-4 py-2 shadow-md">
        <div className="container mx-auto flex items-center justify-between">
          <span className="text-xl font-bold">TSGS OPERA</span>
          <div className="flex space-x-4">
            <Link className="text-gray-600 hover:text-gray-900" href="#">
              Home
            </Link>
            <Link className="text-gray-600 hover:text-gray-900" href="#">
              Events
            </Link>
            <Link className="text-gray-600 hover:text-gray-900" href="#">
              Contact Us
            </Link>
            
          </div>
          <div className="flex space-x-2">
            <Button
              className="border border-gray-300 text-gray-600 hover:border-gray-500 hover:text-gray-900"
              variant="outline">
              Register
            </Button>
            <Button className="bg-blue-600 text-white hover:bg-blue-700" variant="default">
              Login
            </Button>
          </div>
        </div>
      </nav>
      <section className="relative">
        <div
          className="bg-gradient-to-r from-[#3D5685] via-[#9B8F55] to-[#FECB21] py-24 px-4 text-white">
          <div className="container mx-auto flex">
            <img
              alt="Conference Photo"
              className="h-[200px] w-[300px] rounded-lg"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width="300" />
            <div className="ml-8">
              <h1 className="text-3xl font-bold">CISCO The Network Conference Ticket Package</h1>
              <p className="mt-4">
                Look no further! Our CISCO The conference tickets are the simplest way for you to experience a live
                recording.
              </p>
              <Button
                className="mt-6 bg-yellow-400 text-gray-900 hover:bg-yellow-500"
                variant="default">
                Get Ticket
              </Button>
              
            </div>
          </div>
        </div>
      </section>
      <section className="py-8">
        <div className="container mx-auto">
          <h2 className="text-2xl font-bold text-gray-800">Upcoming Events</h2>
          <div className="mt-4 flex space-x-2">
            <Select>
              <SelectTrigger id="weekdays">
                <SelectValue placeholder="Weekdays" />
              </SelectTrigger>
              <SelectContent position="popper">
                <SelectItem value="monday">Monday</SelectItem>
                <SelectItem value="tuesday">Tuesday</SelectItem>
                <SelectItem value="wednesday">Wednesday</SelectItem>
                <SelectItem value="thursday">Thursday</SelectItem>
                <SelectItem value="friday">Friday</SelectItem>
                <SelectItem value="saturday">Saturday</SelectItem>
                <SelectItem value="sunday">Sunday</SelectItem>
              </SelectContent>
            </Select>
            <Select>
              <SelectTrigger id="event-type">
                <SelectValue placeholder="Event Type" />
              </SelectTrigger>
              <SelectContent position="popper">
                <SelectItem value="conference">Conference</SelectItem>
                <SelectItem value="seminar">Seminar</SelectItem>
                <SelectItem value="workshop">Workshop</SelectItem>
              </SelectContent>
            </Select>
            <Select>
              <SelectTrigger id="category">
                <SelectValue placeholder="Category" />
              </SelectTrigger>
              <SelectContent position="popper">
                <SelectItem value="technology">Technology</SelectItem>
                <SelectItem value="business">Business</SelectItem>
                <SelectItem value="education">Education</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="mt-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <Card className="w-full">
              <CardHeader>
                <CardTitle>Event Title</CardTitle>
                <CardDescription>Event description goes here.</CardDescription>
              </CardHeader>
              <CardContent>
                <img
                  alt="Event Image"
                  className="h-[200px] w-full object-cover"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300" />
              </CardContent>
              <CardFooter className="flex justify-between">
                <span>More Info</span>
                <Button variant="outline">Join</Button>
              </CardFooter>
            </Card>
          </div>
          <div className="mt-6 flex justify-center">
            <Button variant="outline">Load More</Button>
          </div>
        </div>
      </section>
      <footer className="bg-gray-900 text-white py-6">
        <div className="container mx-auto grid grid-cols-2 md:grid-cols-4 gap-4">
          <div>
            <h3 className="font-bold">TSGS EVENTS</h3>
            <p className="mt-2 text-sm">
              TSGS provides a platform for leaders in the tech and service industries, and for individuals to share
              their experiences and enrich their lives.
            </p>
            <div className="mt-4 flex space-x-2">
              <FacebookIcon className="text-blue-600" />
              <TwitterIcon className="text-blue-400" />
              <InstagramIcon className="text-pink-600" />
            </div>
          </div>
          <div>
            <h3 className="font-bold">Plan Events</h3>
            <ul className="mt-2 space-y-2">
              <li>Event List</li>
              <li>Calendar</li>
              <li>Locations</li>
            </ul>
          </div>
          <div>
            <h3 className="font-bold">Event Ticket</h3>
            <ul className="mt-2 space-y-2">
              <li>Get Tickets</li>
              <li>Prices</li>
              <li>Locations</li>
              <li>FAQ</li>
            </ul>
          </div>
          <div>
            <h3 className="font-bold">Stay In The Loop</h3>
            <p className="mt-2 text-sm">
              Subscribe to our newsletter to get the latest news, updates, and special offers.
            </p>
            <Input className="mt-4" placeholder="Email" type="email" />
            <Button className="mt-2 bg-blue-600 hover:bg-blue-700" variant="default">
              Subscribe
            </Button>
          </div>
        </div>
      </footer>
    </div>)
  );
}


function FacebookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>)
  );
}


function TwitterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>)
  );
}


function InstagramIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>)
  );
}
